### ISSUE TITLE
Missing instructions to deploy the Config app

### ISSUE THREAD

**Issue by timoleo23** [OfficeDev/microsoft-teams-apps-incidentreport#17]
With the current deployment instructions, you won't be able to authenticate on the configuration webapp with the following authentication error : "application doesn't provide ID tokens" - To fix this issue, the following steps are needed
- Go on Azure portal then Azure AD and App Registration
- Select the App registration of your Configuration app
- Go under "Authentication" and select "Add a platform"
- Select "Web" and then enter the URL of your Config app web app (e.g. https://xxxxxx-config.azurewebsites.net/)
- Check the boxes "Access Token" and "ID tokens"
- Click on "Configure" to save

Then you'll be able to access the configuration web app.

**Comment by v-smahaj** [comment]
Thanks for reporting this issue. We have updated the documentation to include above details.
