### ISSUE TITLE
Deployment Guide - Number of app credentials

### ISSUE THREAD

**Issue by coderkrishna92** [OfficeDev/microsoft-teams-apps-incidentreport#6]
@abbodh Shouldn't there be a total 4 application credentials because of the following:

![image](https://user-images.githubusercontent.com/62812857/79715646-228cba80-8289-11ea-9a79-dca0293ea143.png)

Also, then later on there is this mention: 

![image](https://user-images.githubusercontent.com/62812857/79715667-31736d00-8289-11ea-84cd-c453a86ee8c2.png)

The above screenshot would need to say 4 unique values: 
1. Application ID for the bot
2. Application ID for the config web app
3. Application Secret for the bot
4. Tenant ID - which would be same for bot and config web apps

**Comment by abbodh** [comment]
updated the wiki
